config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
    resources :payment_responses
  end
  namespace :admin do
    resources :payment_requests
  end
  require 'sidekiq/web'
  
 
  

  
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  # devise_scope :user do
  #     get 'sign_in', to: 'devise/sessions#new'
  #     get 'sign_up', to: 'devise/registrations#new'
  # end

  # authenticated :user do
  #   root 'vouchers#index', as: :authenticated_user
  # end

  authenticated :admin do
    mount Sidekiq::Web => '/sidekiq'
    root 'admin/dashboard#index', as: :authenticated_admin
  end


  namespace :admin do
    get 'dashboard/index'
    get '/search', :to => 'search#search'
    resources :register_books
    resources :establishments  do
      resources :pictures
    end
    resources :reviews
    resources :establishment_types do
      get :activate_deactivate_type
    end
    resources :vouchers do
      resources :tags_vouchers
      # get :show_voucher_tags, :to => 'tags#show_voucher_tags'
      # get :create_voucher_tags, :to => 'tags#create_voucher_tags'
    end
    resources :tags
    resources :tags do
      resources :tagpics
    end
    resources :books do 
      get '/search', :to => 'search#search'
    end
   
    resources :users do
      get :mark_as_paid
      get :mark_as_unpaid
    end
  end
  get '/register', :to => "admin/register_books#new"
  
  root 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      # devise_for :users , path: 'users', controllers: { sessions: "users/sessions" }
      get '/sms', :to => 'sms#create'
      get '/establishments/est'

      get '/establishments/hotels'
      get '/establishments/restaurants'
      get '/establishments/spas'
      post '/establishments/get_est' #get a particular est with id

      get '/vouchers/all' #all vouchers
      post '/vouchers/est', :to => 'vouchers#show_for_establishment' #for a particular establishment
      get '/establishment_type/all'
      get '/establishment_type/available_types'
      get 'available/cartegories', :to => 'establishment_type#available_types'

      post '/favourites/add', :to => 'profile#add_favourite'
      get 'favourites', :to => 'profile#all' 

      post '/search/vouchers'

      get 'vouchers/hotels', :to => 'establishment_type#hotel_vouchers'
      get 'vouchers/spas', :to => 'establishment_type#spa_vouchers'
      get 'vouchers/restaurants', :to => 'establishment_type#restaurant_vouchers'
      post 'vouchers/category', :to => 'establishment_type#type'

      get 'discover/tags'

      get '/profile/books'
      get '/profile/redeemed_offers'
      post 'profile/rate'


      post '/pay/mobile'
      post '/pay/from_mpesa'
      get '/pay/from_mpesa'
      post '/pay/check_status'

      post 'redeem/voucher'

      get '/pay/check_book_assingment'

      post '/check', :to => 'social_login#check'

      resources :sms, only: [:create]
      mount_devise_token_auth_for 'User', at: 'auth'
      # resources :users

      jsonapi_resources :vouchers 
    end
  end

end

app/models/tagpic.rb
# == Schema Information
#
# Table name: tagpics
#
#  id                 :uuid             not null, primary key
#  tag_id             :uuid
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Tagpic < ApplicationRecord

	has_attached_file :image, 
					  :path => ':rails_root/public/system/:class/:attachment/:id/:style_:filename',
					  :url => "/system/:class/:attachment/:id/:style_:filename",
					  :styles => { thumb: "200x200", small: "600x600", medium: "800x800" },
					  :default_url => "missing.png"

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	belongs_to :tag
end

app/controllers/admin/tagpics_controller.rb
class Admin::TagpicsController < ApplicationController
  before_action :set_admin_tagpic, only: [:show, :edit, :update, :destroy]

  # GET /admin/tagpics
  # GET /admin/tagpics.json
  def index
    
    @tag = Tag.find(params[:tag_id])
    @tagpics = @tag.tagpics.all
  end

  # GET /admin/tagpics/1
  # GET /admin/tagpics/1.json
  def show
  end

  # GET /admin/tagpics/new
  def new
    @tag = Tag.find(params[:tag_id])
    @tagpic = @tag.tagpics.new
  end

  # GET /admin/tagpics/1/edit
  def edit
  end

  # POST /admin/tagpics
  # POST /admin/tagpics.json
  def create
    # @tagpic = Tagpic.new(admin_tagpic_params)

    @tag = Tag.find(params[:tag_id])
    @tagpic = @tag.tagpics.new

    respond_to do |format|
      if params[:images]

        params[:images].each { |image|
          @tagpic = @tag.tagpics.create(image: image)
        }

        format.html { redirect_to admin_tag_tagpics_path(@tag), notice: 'Tagpic was successfully created.' }
        format.json { render :show, status: :created, location: @tagpic }
      else
        format.html { render :new }
        format.json { render json: @tagpic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/tagpics/1
  # PATCH/PUT /admin/tagpics/1.json
  def update
    @tag = Tag.find(params[:tag_id])
    respond_to do |format|
      if @tagpic.update(admin_tagpic_params)
        format.html { redirect_to admin_tag_tagpics_path(@tag), notice: 'Tagpic was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tagpic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/tagpics/1
  # DELETE /admin/tagpics/1.json
  def destroy
    @tag = Tag.find(params[:tag_id])
    @tagpic.destroy
    respond_to do |format|
      format.html { redirect_to admin_tag_tagpics_path(@tag), notice: 'Tagpic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_tagpic
      @tagpic = Tagpic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_tagpic_params
      params.fetch(:tagpic, {})
      params.require(:tagpic).permit({images: []})
    end
end

app/helpers/admin/tagpics_helper.rb
module Admin::TagpicsHelper
end

app/views/admin/tagpics/_form.html.haml
.row
	.col-md-6
		.box.box-primary
			.box-header.with-border
				%h3.box-title Select files
			%form{:lpformnum => "1", :role => "form"}
			= simple_form_for  @tagpic, :url =>  admin_tag_tagpics_path, html: { multipart: true } do |f|
				= f.error_notification
				.box-body
					.form-group
						%label{:for => "exampleInputFile"} You can select multiple Images
						%br
						= file_field_tag "images[]", type: :file, multiple: true
						%p.help-block Alternatively, you can drag and drop over the choose files button.
				.box-footer
					= f.submit class: "btn btn-primary", value: "Save images"

app/views/admin/tagpics/edit.html.haml
%h1 Editing admin_tagpic

= render 'form'

= link_to 'Show', @admin_tagpic
\|
= link_to 'Back', admin_tagpics_path

app/views/admin/tagpics/index.html.haml
.LoadingOverlay
%h1 Tag name: #{@tag.name}
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Listing Images for this Tag
        .box-tools.pull-right
          / = link_to 'New Picture', new_admin_tag_tagpic_path, class: "btn btn-default"
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
      .row
        .col-sm-12
          %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
            %thead
              %tr{:role => "row"}
                %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 182px;", :tabindex => "0"} Picture 200X200
                %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Description
                %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 113px;", :tabindex => "0"} Options
            %tbody
              - if @tagpics.present?
                - @tagpics.each do |tag_tagpic|

                  %tr{:class => "#{cycle('even', 'odd')}"}
                    %td.sorting_1= image_tag tag_tagpic.image.url(:small)
                    / %td= tag_tagpic.description
                    %td
                      -if current_admin && current_admin.is_admin?
                        / = link_to 'Add desc',edit_admin_tag_tagpic_path(id: tag_tagpic.id), class: "label label-default"
                        = link_to 'Delete', admin_tag_tagpic_path(id: tag_tagpic.id), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"

%br

-if current_admin && current_admin.is_previlaged?
  = link_to 'New Picture', new_admin_tag_tagpic_path, class: "btn btn-primary"

= link_to 'Back', admin_tags_path, class: "btn btn-default"

app/views/admin/tagpics/new.html.haml
%section.content-header
	%h1 Adding pictures to tag:  #{@tag.name}

%section.content
	= render 'form'

= link_to 'Back', admin_tag_tagpics_path, class: "label label-default"

app/views/admin/tagpics/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_tagpic_path(@admin_tagpic), class: "btn btn-default"
\|
= link_to 'Back', admin_tagpics_path, class: "btn btn-primary"