config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
    resources :payment_responses
  end
  namespace :admin do
    resources :payment_requests
  end
  require 'sidekiq/web'
  
 
  

  
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  # devise_scope :user do
  #     get 'sign_in', to: 'devise/sessions#new'
  #     get 'sign_up', to: 'devise/registrations#new'
  # end

  # authenticated :user do
  #   root 'vouchers#index', as: :authenticated_user
  # end

  authenticated :admin do
    mount Sidekiq::Web => '/sidekiq'
    root 'admin/dashboard#index', as: :authenticated_admin
  end


  namespace :admin do
    get 'dashboard/index'
    get '/search', :to => 'search#search'
    resources :register_books
    resources :establishments  do
      resources :pictures
    end
    resources :reviews
    resources :establishment_types do
      get :activate_deactivate_type
    end
    resources :vouchers do
      resources :tags_vouchers
      # get :show_voucher_tags, :to => 'tags#show_voucher_tags'
      # get :create_voucher_tags, :to => 'tags#create_voucher_tags'
    end
    resources :tags
    resources :tags do
      resources :tagpics
    end
    resources :books do 
      get '/search', :to => 'search#search'
    end
   
    resources :users do
      get :mark_as_paid
      get :mark_as_unpaid
    end
  end
  get '/register', :to => "admin/register_books#new"
  
  root 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      # devise_for :users , path: 'users', controllers: { sessions: "users/sessions" }
      get '/sms', :to => 'sms#create'
      get '/establishments/est'

      get '/establishments/hotels'
      get '/establishments/restaurants'
      get '/establishments/spas'
      post '/establishments/get_est' #get a particular est with id

      get '/vouchers/all' #all vouchers
      post '/vouchers/est', :to => 'vouchers#show_for_establishment' #for a particular establishment
      get '/establishment_type/all'
      get '/establishment_type/available_types'
      get 'available/cartegories', :to => 'establishment_type#available_types'

      post '/favourites/add', :to => 'profile#add_favourite'
      get 'favourites', :to => 'profile#all' 

      post '/search/vouchers'

      get 'vouchers/hotels', :to => 'establishment_type#hotel_vouchers'
      get 'vouchers/spas', :to => 'establishment_type#spa_vouchers'
      get 'vouchers/restaurants', :to => 'establishment_type#restaurant_vouchers'
      post 'vouchers/category', :to => 'establishment_type#type'

      get 'discover/tags'

      get '/profile/books'
      get '/profile/redeemed_offers'
      post 'profile/rate'


      post '/pay/mobile'
      post '/pay/from_mpesa'
      get '/pay/from_mpesa'
      post '/pay/check_status'

      post 'redeem/voucher'

      get '/pay/check_book_assingment'

      post '/check', :to => 'social_login#check'

      resources :sms, only: [:create]
      mount_devise_token_auth_for 'User', at: 'auth'
      # resources :users

      jsonapi_resources :vouchers 
    end
  end

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :uuid             not null, primary key
#  code       :string
#  year       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  registered :boolean          default(FALSE), not null
#

class Book < ApplicationRecord
	has_one  :register_book
	has_many :details, dependent: :destroy
	has_many :establishments, through: :details
	has_many :vouchers, through: :establishments

	# including elastic search
	# include Elasticsearch::Model
    #  	include Elasticsearch::Model::Callbacks

  	searchkick #using searchkick gem instead

    # SearchKick 
	def search_data
	  { 
	  	code: code
	  }
	end

	def registered?
		if self.register_book
			return self.register_book
		else
			return false
		end
	end

	def registered_already?
		if self.register_book.present?
			return true
		else
			return false
		end
	end

	def book_code
		"#{self.code}"
	end

	def self.is_registered book_code
		# check if the book is retistered aand return the registered book
		book = RegisterBook.where(book_code: "#{book_code}").first
		if book.nil?
			p "THis book is not registered"
			return false
		else
			"The book is registered"
			return book
		end
	end

	def self.get_unregistered_book_for_mobile_user
		
		book = Book.where(registered: false).order("RANDOM()").first

		if book
			return book
		else
			return false
		end
		
	end

	# the ree book, owned by dennorina@gmail.com, used for the one free voucher.
	def self.free_book
		book = Book.where(code:"DISCOUCHERFREEBOOK").first
		return book
	end
	
end

app/controllers/admin/books_controller.rb
class  Admin::BooksController < Admin::ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.paginate(:page => params[:page], :per_page => 20)
    # lables = FailedRedemption.group_by_month(:created_at).count
    # 
    # Establishment Visits By Location
    labels =  Establishment.select(:location).joins(:visits).select(:location)
    array_of_data_one = labels.to_a.group_by(&:location).map {|label, data| data.count}
    colour = []
    array_of_data_one.size.times { |c| colour <<"#%06x" % (rand * 0xffffff) }

    # Establishment Visits By name
    labels2 =  Establishment.select(:name).joins(:visits).select(:name)
    array_of_data_two = labels2.to_a.group_by(&:name).map {|name, data| data.count}
    colour2 = []
    array_of_data_two.size.times { |c| colour2 <<"#%06x" % (rand * 0xffffff) }

    @data = {
      labels: ['Westlands', 'Nairobi CBD', 'Outside Nairobi', 'Karen', 'Ngong Road'],#labels.to_a.group_by(&:location).map {|label, data| label},
      datasets: [
        {
           # label: "My First dataset",
           # pointStrokeColor: "#FFA500",
           # fillColor: "rgba(255,165,0,0.5)",
           # pointColor: "rgba(255,165,0,1)",
           # strokeColor: "rgba(255,165,0,1)",
           data: [10,12,50,100,60],#array_of_data_one,
           backgroundColor: colour,
           hoverBackgroundColor: "#FFA500"

        }
      ]
    }
    @establishment_vistis_by_name = {
      labels: ['Java', 'Chicken Inn', 'Pizza Inn', 'Red Carpet','About Thyme'] ,#labels2.to_a.group_by(&:name).map {|name, data| name},
      datasets: [
        {
           # label: "My First dataset",
           # pointStrokeColor: "#FFA500",
           # fillColor: "rgba(255,165,0,0.5)",
           # pointColor: "rgba(255,165,0,1)",
           # strokeColor: "rgba(255,165,0,1)",
           data: [44,55,90,11,76],#array_of_data_two,
           backgroundColor: colour2,
           hoverBackgroundColor: "#FFA500"

        }
      ]
    }

    # Books Registered this week
    labels3 = RegisterBook.group_by_month(:created_at).count
    array_of_data_three = labels3.to_a.map {|name, data| data}
    colour3 = []
    array_of_data_three.size.times { |c| colour3 <<"#%06x" % (rand * 0xffffff) }

    @registered_book_data = {
      labels: ['January', 'Febraury', 'March'],#labels3.to_a.map {|label, data| label.strftime("%B")},
      datasets: [
        {
           # label: "My First dataset",
           # pointStrokeColor: "#FFA500",
           # fillColor: "rgba(255,165,0,0.5)",
           # pointColor: "rgba(255,165,0,1)",
           # strokeColor: "rgba(255,165,0,1)",
           data: [3,2,7], #array_of_data_three,
           backgroundColor: colour3,
           hoverBackgroundColor: "#FFA500"

        }
      ]
    }

    # Visits by month
    labels4 = Visit.select(:establishment_id, :created_at).to_a.group_by_month(&:created_at)

    array_of_data_four = labels4.map {|name, data| data.count}
    colour4 = []
    array_of_data_four.size.times { |c| colour4 <<"#%06x" % (rand * 0xffffff) }

    @visits_by_month = {
      labels: ['January', 'Febraury', 'March'],#labels4.to_a.map {|label, data| label.strftime("%B")},
      datasets: [
        {
           # label: "My First dataset",
           # pointStrokeColor: "#FFA500",
           # fillColor: "rgba(255,165,0,0.5)",
           # pointColor: "rgba(255,165,0,1)",
           # strokeColor: "rgba(255,165,0,1)",
           data: [3,2,7],#array_of_data_four,
           backgroundColor: colour4,
           hoverBackgroundColor: "#FFA500"

        }
      ]
    }

    @options1 = {:height => "257px", :width => "514px"}
    @options2 = {:height => "257px", :width => "514px"}
    @options3 = {:height => "257px", :width => "514px"}
    @options4 = {:height => "257px", :width => "514px"}
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  def registration
    @book = Book.find(params[:id])
  end
  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    # est_ids = Establishment.all.pluck(:id) # adding all establishments automatically
    @book.establishments << Establishment.all # not efficient code. later add a worker to do this
    respond_to do |format|
      if @book.save
        # update Establishments
        # byebug
        format.html { redirect_to admin_book_url(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
     
        format.html { redirect_to admin_book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to admin_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # 
    # Names of establishments visited by customers (Larna visited Java, Palanka this month/ btn jan and feb)
    # 
    
    # 
    # Total voucher redeemed in all establishments
    # 
    # least visited establishments
    # 
    # 
    # most active Establishment
    def most_visited_establishment
      v = Establishment.select(:name).joins(:visits).select(:name).to_a.group_by(&:name)
      names =  v.map {|name, data|  names}
      data = v.map {|name, data|  data.count}
      hash = Hash[*names.zip(data).flatten]
      return hash
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      est_ids = Establishment.all.pluck(:id) # adding all establishments automatically
      
      params.require(:book).permit(:code, :year, {establishment_ids: []})
      # byebug
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_chart.haml
.row-fluid
  .col-md-6
    .box.box-danger
      .box-header.with-border
        %h3.box-title Establishment Visits By Location
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        = doughnut_chart @data , @options1
.row-fluid
  .col-md-6
    .box.box-danger
      .box-header.with-border
        %h3.box-title Establishment Visits By name
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        / = doughnut_chart @data, @options1
        = doughnut_chart @establishment_vistis_by_name, @options2

.row-fluid
  .col-md-6
    .box.box-danger
      .box-header.with-border
        %h3.box-title Book Registration By Month
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        / = doughnut_chart @data, @options1
        = line_chart @registered_book_data , @options3
.row-fluid
  .col-md-6
    .box.box-danger
      .box-header.with-border
        %h3.box-title Establishment Visits By month
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        / = doughnut_chart @data, @options1
        = line_chart @visits_by_month , @options4

app/views/admin/books/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Books In the Database
        .box-tools.pull-right
          .digg_pagination
            = will_paginate books 
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            %br
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 182px;", :tabindex => "0"} Book Code
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Year
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Number of Est
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 156px;", :tabindex => "0"} Registration Status
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 113px;", :tabindex => "0"} Options
                %tbody
                  - books.each do |book|
                    
                    %tr{:class => "#{cycle('even', 'odd')}"}
                      %td.sorting_1= book.code
                      %td= book.year
                      %td= book.establishments.count
                      %td
                        -if book.registered_already?
                          = link_to 'registered', '#', class: "label label-success"
                        -else
                          = link_to 'unregistered', '#', class: "label label-default"
                      %td 
                        -if current_admin && current_admin.is_admin?
                          = link_to 'Edit', edit_admin_book_path(book), class: "label label-default"
                          = link_to "Show",admin_book_path(book), class: "label label-warning"
                          = link_to 'Delete', admin_book_path(book), :method => :delete, :data => { :confirm => 'This will destroy associated models, Are you sure?' }, class: "label label-danger"

                %tfoot
                  %tr
                    %th{:colspan => "1", :rowspan => "1"} Establishment Name
                    %th{:colspan => "1", :rowspan => "1"} Location
                    %th{:colspan => "1", :rowspan => "1"} Area
                    %th{:colspan => "1", :rowspan => "1"} Contact Phone
                    %th{:colspan => "1", :rowspan => "1"} Options
          .row
            .col-sm-5
              .page_info
                = page_entries_info books
            .col-sm-7
              .digg_pagination
                = will_paginate books 
      / /.box-body
    / /.box
  / /.col

app/views/admin/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @admin_book, class: "label label-default"
\|
= link_to 'Back', admin_books_path, class: "label label-primary"

app/views/admin/books/index.html.haml
/ Content Header (Page header)
%section.content-header
  %h1
    DisCoucher Books
    %small All Books in the database
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Level
    %li.active Here

%br

.row-fluid
  .col-md-12
    .box.box-danger
      .box-header.with-border
        %h3.box-title 
        Vists per Establishment (Vouchers redeemed per establishment)
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          / %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
          /   %i.fa.fa-times
      .box-body
        =render "admin/books/chart", books: @books

#partial_page
  =render "admin/books/table", books: @books #the table that was previously here was extracted to the partial to be DRY. seems like I needed it more than I thought! :-)

-if current_admin && current_admin.is_previlaged?
  %p=link_to 'New Book', new_admin_book_path, class: "btn btn-primary"

app/views/admin/books/index.js.erb
$('.pagination a').attr('data-remote', 'true');
$("#partial_page").html("<%= escape_javascript(render partial:'table', locals: {books: @books}) %>");

app/views/admin/books/new.html.haml
/ Content Header (Page header)
/ %section.content-header
/   %h1
/     New book
/     %small Create a new book
/   %ol.breadcrumb
/     %li
/       %a{:href => "#"}
/         %i.fa.fa-dashboard
/         Level
/     %li.active Here

= render 'form'

= link_to 'Back', admin_books_path

app/views/admin/books/registration.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %title AdminLTE 2 | Log in
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    = csrf_meta_tags
  %body.login-page
    .login-box
      .login-logo
        %a{:href => "/"}
          %b> Admin
          LTE
      / /.login-logo
      .login-box-body
        %p.login-box-msg Sign upto start your session
        = simple_form_for @book do |f|
          = f.error_notification
          .form-group.has-feedback
            = f.input :email, class: 'form-control', placeholder: 'Email',autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :first_name, class: 'form-control', placeholder: 'First name', autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :last_name, class: 'form-control', placeholder: 'Last name',autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :phone_number, class: 'form-control', placeholder: 'Phone Number',autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :password, class: 'form-control', placeholder: 'Password',autocomplete: 'off' ,label: false
            %span.glyphicon.glyphicon-lock.form-control-feedback
          .form-group.has-feedback
            = f.input :password_confirmation, class: 'form-control',placeholder: 'Retype password' ,autocomplete: 'off', label: false
            %span.glyphicon.glyphicon-lock.form-control-feedback
          .row
            .col-xs-8
              .checkbox.icheck
                %label
                  %input{:type => "checkbox"}/
                  Remember Me
            / /.col
            .col-xs-4
              = f.button :submit, 'Register', class: 'btn btn-primary btn-block btn-flat'
            / /.col
      / /.login-box-body
    / /.login-box
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %title AdminLTE 2 | Log in
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    = csrf_meta_tags
  %body.login-page
    .login-box
      .login-logo
        %a{:href => "/"}
          %b> Admin
          LTE
      / /.login-logo
      .login-box-body
        %p.login-box-msg Sign upto start your session
        = simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
          = f.error_notification
          .form-group.has-feedback
            = f.input :email, class: 'form-control', placeholder: 'Email',autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :first_name, class: 'form-control', placeholder: 'First name', autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :last_name, class: 'form-control', placeholder: 'Last name',autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :phone_number, class: 'form-control', placeholder: 'Phone Number',autofocus: true, label: false
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :password, class: 'form-control', placeholder: 'Password',autocomplete: 'off' ,label: false
            %span.glyphicon.glyphicon-lock.form-control-feedback
          .form-group.has-feedback
            = f.input :password_confirmation, class: 'form-control',placeholder: 'Retype password' ,autocomplete: 'off', label: false
            %span.glyphicon.glyphicon-lock.form-control-feedback
          .row
            .col-xs-8
              .checkbox.icheck
                %label
                  %input{:type => "checkbox"}/
                  Remember Me
            / /.col
            .col-xs-4
              = f.button :submit, 'Register', class: 'btn btn-primary btn-block btn-flat'
            / /.col
      / /.login-box-body
    / /.login-box
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/admin/books/show.html.haml
/ .section
/   .row
/     .col-md-4
/       / Widget: user widget style 1
/       .box.box-widget.widget-user-2
/         / Add the bg color to the header using any of the bg-* classes
/         .widget-user-header.bg-yellow
/           .widget-user-image
/             %img.img-circle{:alt => "User Avatar", :src => "/assets/user.jpg"}/
/           / /.widget-user-image
/           %h3.widget-user-username Nadia Carmichael
/           %h5.widget-user-desc Lead Developer
/         .box-footer.no-padding
/           %ul.nav.nav-stacked
/             %li
/               %a{:href => "#"}
/                 Projects
/                 %span.pull-right.badge.bg-blue 31
/             %li
/               %a{:href => "#"}
/                 Tasks
/                 %span.pull-right.badge.bg-aqua 5
/             %li
/               %a{:href => "#"}
/                 Completed Projects
/                 %span.pull-right.badge.bg-green 12
/             %li
/               %a{:href => "#"}
/                 Followers
/                 %span.pull-right.badge.bg-red 842
/       / /.widget-user
/     .col-md-4
/       / Widget: user widget style 1
/       .box.box-widget.widget-user
/         / Add the bg color to the header using any of the bg-* classes
/         .widget-user-header.bg-aqua-active
/           %h3.widget-user-username Alexander Pierce
/           %h5.widget-user-desc Founder &amp; CEO
/         .widget-user-image
/           %img.img-circle{:alt => "User Avatar", :src => "/assets/user.jpg"}/
/         .box-footer
/           .row
/             .col-sm-4.border-right
/               .description-block
/                 %h5.description-header 3,200
/                 %span.description-text SALES
/               / /.description-block
/             / /.col
/             .col-sm-4.border-right
/               .description-block
/                 %h5.description-header 13,000
/                 %span.description-text FOLLOWERS
/               / /.description-block
/             / /.col
/             .col-sm-4
/               .description-block
/                 %h5.description-header 35
/                 %span.description-text PRODUCTS
/               / /.description-block
/             / /.col
/           / /.row
/       / /.widget-user




.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Book Code: #{@book.code},  Year #{@book.year}
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            .col-sm-5
            .col-sm-7
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 182px;", :tabindex => "0"} Establishment
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Location
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} No. of Vouchers
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 156px;", :tabindex => "0"} Registration Status
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 113px;", :tabindex => "0"} Options
                %tbody
                  - @book.establishments.each do |establishment|
                    %tr
                      %td= establishment.name
                      %td= establishment.location
                      %td= establishment.vouchers.count
                      %td


/ %table.table.table-hover
/   %thead
/     %tr
/       %th establishment
/       %th Location
/       %th No. of Vouchers
/       %th

/   %tbody
/     - @book.establishments.each do |establishment|
/       %tr
/         %td= establishment.name
/         %td= establishment.location
/         %td= establishment.vouchers.count
/         %td
/           -if current_admin && current_admin.is_admin?
/             = link_to 'Edit', edit_establishment_path(establishment), class: "label label-default"
/             = link_to "Show",establishment, class: "label label-warning"
/             = link_to 'Delete', establishment, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"
.table.table.table-bordered.text-center
  %tbody
    %tr
      %td
        = link_to 'Edit', edit_admin_book_path(@book), class: "btn btn-block btn-default"

      %td
        = link_to 'Back', admin_books_path, class: "btn btn-block btn-primary"
        
/ = link_to 'Back', admin_books_path