config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
    resources :payment_responses
  end
  namespace :admin do
    resources :payment_requests
  end
  require 'sidekiq/web'
  
 
  

  
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  # devise_scope :user do
  #     get 'sign_in', to: 'devise/sessions#new'
  #     get 'sign_up', to: 'devise/registrations#new'
  # end

  # authenticated :user do
  #   root 'vouchers#index', as: :authenticated_user
  # end

  authenticated :admin do
    mount Sidekiq::Web => '/sidekiq'
    root 'admin/dashboard#index', as: :authenticated_admin
  end


  namespace :admin do
    get 'dashboard/index'
    get '/search', :to => 'search#search'
    resources :register_books
    resources :establishments  do
      resources :pictures
    end
    resources :reviews
    resources :establishment_types do
      get :activate_deactivate_type
    end
    resources :vouchers do
      resources :tags_vouchers
      # get :show_voucher_tags, :to => 'tags#show_voucher_tags'
      # get :create_voucher_tags, :to => 'tags#create_voucher_tags'
    end
    resources :tags
    resources :tags do
      resources :tagpics
    end
    resources :books do 
      get '/search', :to => 'search#search'
    end
   
    resources :users do
      get :mark_as_paid
      get :mark_as_unpaid
    end
  end
  get '/register', :to => "admin/register_books#new"
  
  root 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      # devise_for :users , path: 'users', controllers: { sessions: "users/sessions" }
      get '/sms', :to => 'sms#create'
      get '/establishments/est'

      get '/establishments/hotels'
      get '/establishments/restaurants'
      get '/establishments/spas'
      post '/establishments/get_est' #get a particular est with id

      get '/vouchers/all' #all vouchers
      post '/vouchers/est', :to => 'vouchers#show_for_establishment' #for a particular establishment
      get '/establishment_type/all'
      get '/establishment_type/available_types'
      get 'available/cartegories', :to => 'establishment_type#available_types'

      post '/favourites/add', :to => 'profile#add_favourite'
      get 'favourites', :to => 'profile#all' 

      post '/search/vouchers'

      get 'vouchers/hotels', :to => 'establishment_type#hotel_vouchers'
      get 'vouchers/spas', :to => 'establishment_type#spa_vouchers'
      get 'vouchers/restaurants', :to => 'establishment_type#restaurant_vouchers'
      post 'vouchers/category', :to => 'establishment_type#type'

      get 'discover/tags'

      get '/profile/books'
      get '/profile/redeemed_offers'
      post 'profile/rate'


      post '/pay/mobile'
      post '/pay/from_mpesa'
      get '/pay/from_mpesa'
      post '/pay/check_status'

      post 'redeem/voucher'

      get '/pay/check_book_assingment'

      post '/check', :to => 'social_login#check'

      resources :sms, only: [:create]
      mount_devise_token_auth_for 'User', at: 'auth'
      # resources :users

      jsonapi_resources :vouchers 
    end
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id                 :uuid             not null, primary key
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Tag < ApplicationRecord


	has_many :tagpics, dependent: :destroy
	has_and_belongs_to_many :vouchers
	before_save { |tag| tag.name = tag.name.downcase }

	searchkick

	def search_data
	  { 
	  	name: name
	  }
	end


	def featured_image

		if Rails.env == "development" 
			root_url = "http://localhost:3000"
		else
			root_url = "http://159.89.103.53"
		end


		tagpic = self.tagpics

		if tagpic.present?
			image = root_url + tagpic.first.image.url(:medium)
		else
			image = nil
		end
		
		# image = root_url + tagpic
		return image
	end

	def self.get_vouchers tags

		vouchers_collection = []
		tags.each do |tag|
			tag.vouchers.each do |voucher|
				vouchers_collection << voucher
			end
		end
		return vouchers_collection
	end


	def self.dup
		tagS = []
		tags  = []
		codes = []
		regex = /[[:upper:]]/
		Tag.all.each do |tag|
		  small_tag_name = tag.name.downcase
		  capital_tag_name = tag.name.titlecase

		  # search
		  small = Tag.where(name: "#{small_tag_name}")
		  caps = Tag.where(name: "#{capital_tag_name}")
		  
		  if small.count >= 1 && caps.count >=1


		  	# if small.count > caps.count

		  	# elsif caps.count > small.count

		  	# end
		  			
		  	# 

		  	tagS << caps.first.vouchers.count
		  	
		  	tags << small.first.vouchers.count
		  	
		  end
		end

		return tags, tagS
	end
end

app/controllers/admin/tags_vouchers_controller.rb
class Admin::TagsVouchersController < ApplicationController
  before_action :set_admin_tags_voucher, only: [:show, :edit, :update, :destroy]

  # GET /admin/tags_vouchers
  # GET /admin/tags_vouchers.json
   def index
      @voucher = Voucher.find(params[:voucher_id])
      @tags = @voucher.tags.paginate(:page => params[:page], :per_page => 20)
  end

  # def show_voucher_tags
  #   @voucher = Voucher.find(params[:voucher_id])
  #   @tags = @voucher.tags.paginate(:page => params[:page], :per_page => 20)
  # end

  # GET /admin/tags/1
  # GET /admin/tags/1.json
  def show
    
  end

  # GET /admin/tags/new
  def new
    @tag = Tag.new
    @voucher = Voucher.find(params[:voucher_id])
  end

  # GET /admin/tags/1/edit
  def edit
  end

  # POST /admin/tags
  # POST /admin/tags.json
  def create
    
    # if params[:voucher_ids]
    # byebug
      @voucher = Voucher.find(params[:tag][:voucher_ids])
    # else
      @tag =  Tag.new(tag_params)
    # end
     
    respond_to do |format|
      if  @tag.save
        
        # check if some images have been uploaded.
        if params[:images]
          #===== The magic is here ;)
          params[:images].each { |image|
            @tag.tagpics.create(image: image)
          }
        end

        @voucher.tags << @tag # populate the join table for the many to many relationship.

        format.html { redirect_to  admin_tags_url(@tag), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location:  @tag }
      else
        format.html { render :new }
        format.json { render json:  @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/tags/1
  # PATCH/PUT /admin/tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to admin_tags_url(@tag), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/tags/1
  # DELETE /admin/tags/1.json
  def destroy
    @voucher = Voucher.find(params[:voucher_id])

    @voucher.tags.delete(@tag)
     # @tag.destroy
    respond_to do |format|
      format.html { redirect_to admin_voucher_tags_vouchers_url, notice: 'Voucher was successfully untagged.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_tags_voucher
       @tag =  Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name,{voucher_ids: []} ,{images: []})
    end
end

app/helpers/admin/tags_vouchers_helper.rb
module Admin::TagsVouchersHelper
end

app/views/admin/tags_vouchers/_form.html.haml
.row
	.col-md-6
		.box.box-primary
			.box-header.with-border
				%h3.box-title Select files
			%form{:lpformnum => "1", :role => "form"}
			= simple_form_for  @tag, :url =>  admin_voucher_tags_vouchers_path, html: { multipart: true } do |f|
				= f.error_notification
				.box-body
					.row
						.col-md-6
							.form-group
								%label{:for => "exampleInputPassword1"} Tag Name
								= f.text_field :name, class: "form-control", placeholder: "Enter Tag Name"
						.col-md-6
							.form-group
								%label{:for => "exampleInputPassword1"} Voucher Code
								= f.select :voucher_ids, :selected => params[:voucher_id]
								/ = f.text_field :name, class: "form-control", placeholder: "Enter Tag Name"
						.col-md-6
							.form-group
								%label{:for => "exampleInputFile"} You can select multiple Images
								%br
								= file_field_tag "images[]", type: :file, multiple: true
								%p.help-block Alternatively, you can drag and drop over the choose files button.
				.box-footer
					= f.submit class: "btn btn-primary", value: "Save images"

app/views/admin/tags_vouchers/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Tags
        .box-tools.pull-right
          .digg_pagination
            = will_paginate tags 
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            %br
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 182px;", :tabindex => "0"} tag Name
                    / %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Location
                    / %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 80px;", :tabindex => "0"} Area
                    / %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 156px;", :tabindex => "0"} Contact Phone
                    / %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 80px;", :tabindex => "0"} Address
                    / %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 156px;", :tabindex => "0"} Logo
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 250px;", :tabindex => "0"} Options
                %tbody
                  - tags.each do |tag|

                    %tr{:class => "#{cycle('even', 'odd')}"}
                      %td.sorting_1= tag.name
                      / %td= tag.location
                      / %td= tag.area
                      / %td= tag.phone
                      / %td= tag.address
                      / %td= image_tag tag.logo.url(:small)
                      %td 
                        -if current_admin && current_admin.is_previs_previlaged?
                          = link_to 'Edit', edit_admin_tag_path(tag), class: "label label-default"
                          = link_to "Details", admin_tag_path(tag), class: "label label-warning"
                          = link_to 'Untag', admin_voucher_tags_voucher_path(:id => tag.id), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"
                          = link_to "Images", admin_tag_tagpics_path(tag), class: "label label-success"

                %tfoot
                  %tr
                    %th{:colspan => "1", :rowspan => "1"} tag Name
                    %th{:colspan => "1", :rowspan => "1"} Options
          .row
            .col-sm-5
              .page_info
                = page_entries_info tags
            .col-sm-7
              .digg_pagination
                = will_paginate tags 
      / /.box-body
    / /.box
  / /.col

app/views/admin/tags_vouchers/edit.html.haml
%h1 Editing admin_tags_voucher

= render 'form'

= link_to 'Show', @admin_tags_voucher
\|
= link_to 'Back', admin_tags_vouchers_path

app/views/admin/tags_vouchers/index.html.haml
%section.content-header
  %h1
    DisCoucher Tags
    %small All Tags For Voucher Code:::  #{@voucher.code}
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Level
    %li.active Here


%br


%br
#partial_page
  =render "admin/tags_vouchers/table", tags: @tags #the table that was previously here was extracted to the partial to be DRY. seems like I needed it more than I thought! :-)

%br
-if current_admin && current_admin.is_previlaged?
  %p=link_to 'Add New Tag to this Voucher', new_admin_voucher_tags_voucher_path(@voucher.id), class: "btn btn-primary"

app/views/admin/tags_vouchers/new.html.haml
%h1 New Tag for voucher: #{@voucher.code}

= render 'form'

= link_to 'Back', admin_voucher_tags_vouchers_path

app/views/admin/tags_vouchers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_tags_voucher_path(@admin_tags_voucher),class: "btn btn-default"
\|
= link_to 'Back', admin_tags_vouchers_path,class: "btn btn-primary"