config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
    resources :payment_responses
  end
  namespace :admin do
    resources :payment_requests
  end
  require 'sidekiq/web'
  
 
  

  
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  # devise_scope :user do
  #     get 'sign_in', to: 'devise/sessions#new'
  #     get 'sign_up', to: 'devise/registrations#new'
  # end

  # authenticated :user do
  #   root 'vouchers#index', as: :authenticated_user
  # end

  authenticated :admin do
    mount Sidekiq::Web => '/sidekiq'
    root 'admin/dashboard#index', as: :authenticated_admin
  end


  namespace :admin do
    get 'dashboard/index'
    get '/search', :to => 'search#search'
    resources :register_books
    resources :establishments  do
      resources :pictures
    end
    resources :reviews
    resources :establishment_types do
      get :activate_deactivate_type
    end
    resources :vouchers do
      resources :tags_vouchers
      # get :show_voucher_tags, :to => 'tags#show_voucher_tags'
      # get :create_voucher_tags, :to => 'tags#create_voucher_tags'
    end
    resources :tags
    resources :tags do
      resources :tagpics
    end
    resources :books do 
      get '/search', :to => 'search#search'
    end
   
    resources :users do
      get :mark_as_paid
      get :mark_as_unpaid
    end
  end
  get '/register', :to => "admin/register_books#new"
  
  root 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      # devise_for :users , path: 'users', controllers: { sessions: "users/sessions" }
      get '/sms', :to => 'sms#create'
      get '/establishments/est'

      get '/establishments/hotels'
      get '/establishments/restaurants'
      get '/establishments/spas'
      post '/establishments/get_est' #get a particular est with id

      get '/vouchers/all' #all vouchers
      post '/vouchers/est', :to => 'vouchers#show_for_establishment' #for a particular establishment
      get '/establishment_type/all'
      get '/establishment_type/available_types'
      get 'available/cartegories', :to => 'establishment_type#available_types'

      post '/favourites/add', :to => 'profile#add_favourite'
      get 'favourites', :to => 'profile#all' 

      post '/search/vouchers'

      get 'vouchers/hotels', :to => 'establishment_type#hotel_vouchers'
      get 'vouchers/spas', :to => 'establishment_type#spa_vouchers'
      get 'vouchers/restaurants', :to => 'establishment_type#restaurant_vouchers'
      post 'vouchers/category', :to => 'establishment_type#type'

      get 'discover/tags'

      get '/profile/books'
      get '/profile/redeemed_offers'
      post 'profile/rate'


      post '/pay/mobile'
      post '/pay/from_mpesa'
      get '/pay/from_mpesa'
      post '/pay/check_status'

      post 'redeem/voucher'

      get '/pay/check_book_assingment'

      post '/check', :to => 'social_login#check'

      resources :sms, only: [:create]
      mount_devise_token_auth_for 'User', at: 'auth'
      # resources :users

      jsonapi_resources :vouchers 
    end
  end

end

app/controllers/admin/establishment_types_controller.rb
class Admin::EstablishmentTypesController < ApplicationController
  before_action :set_admin_establishment_type, only: [:show, :edit, :update, :destroy]

  # GET /admin/establishment_types
  # GET /admin/establishment_types.json
  def index
    @admin_establishment_types =  EstablishmentType.all.order('name ASC').paginate(:page => params[:page], :per_page => 20)
  end

  # GET /admin/establishment_types/1
  # GET /admin/establishment_types/1.json
  def show
  end

  # GET /admin/establishment_types/new
  def new
    @admin_establishment_type =  EstablishmentType.new
  end

  # GET /admin/establishment_types/1/edit
  def edit
  end

  # POST /admin/establishment_types
  # POST /admin/establishment_types.json
  def create
    @admin_establishment_type =  EstablishmentType.new(admin_establishment_type_params)

    respond_to do |format|
      if @admin_establishment_type.save
        format.html { redirect_to admin_establishment_types_url(@admin_establishment_type), notice: 'Establishment type was successfully created.' }
        format.json { render :show, status: :created, location: @admin_establishment_type }
      else
        format.html { render :new }
        format.json { render json: @admin_establishment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/establishment_types/1
  # PATCH/PUT /admin/establishment_types/1.json
  def update
    respond_to do |format|
      if @admin_establishment_type.update(admin_establishment_type_params)
        format.html { redirect_to admin_establishment_types_url, notice: 'Establishment type was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_establishment_type }
      else
        format.html { render :edit }
        format.json { render json: @admin_establishment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/establishment_types/1
  # DELETE /admin/establishment_types/1.json
  def destroy
    @admin_establishment_type.destroy
    respond_to do |format|
      format.html { redirect_to admin_establishment_types_url, notice: 'Establishment type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate_deactivate_type

    @type = EstablishmentType.find(params[:establishment_type_id])
    activate = @type.activate_deactivate_est_availablity
    respond_to do |format|
      if activate == false
        format.html { redirect_to admin_establishment_types_url, alert: 'Sorry, something went wrong!' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to admin_establishment_types_url, notice: 'This type is now available to users.'}
        format.json { render :show, status: :created, location: @user }
      end
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_establishment_type
      @admin_establishment_type =  EstablishmentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_establishment_type_params
      params.require(:establishment_type).permit(:name, :description)
    end
end

app/controllers/api/v1/establishment_type_controller.rb
class Api::V1::EstablishmentTypeController < Api::V1::BaseController
	before_action :authenticate_api_v1_user!, only: [:me]
	before_action :ensure_voucher_params_exists, only:[:type]


	def all
		@est_type = EstablishmentType.all.paginate(:page => params[:page], :per_page => 10)
		
		render jsonapi: @est_type, class: { EstablishmentType: Api::V1::SerializableEstablishmentType }
		
	end

	def available_types
		@types = EstablishmentType.where(available: true)

		# return render_data @types
		render jsonapi: @types, class: { EstablishmentType: Api::V1::SerializableEstablishmentType }
	end

	def type

		est_type = EstablishmentType.where(name: params[:name]).first

			# byebug
		type_vouchers = paginate est_type.vouchers.order("RANDOM()"), per_page: 30

		# render jsonapi: hotel_vouchers, class: { Voucher: Api::V1::SerializableVoucher }

		context = { user: current_api_v1_user}
		@voucher_resources = type_vouchers.map { |voucher| Api::V1::VoucherResource.new(voucher, context) }

		render json: JSONAPI::ResourceSerializer.new(Api::V1::VoucherResource).serialize_to_hash(@voucher_resources)
	end

	def hotel_vouchers
		hotel = EstablishmentType.where(name: "hotels").first

		hotel_vouchers = paginate hotel.vouchers.order("RANDOM()"), per_page: 30

		# render jsonapi: hotel_vouchers, class: { Voucher: Api::V1::SerializableVoucher }

		context = { user: current_api_v1_user}
		@voucher_resources = hotel_vouchers.map { |voucher| Api::V1::VoucherResource.new(voucher, context) }

		render json: JSONAPI::ResourceSerializer.new(Api::V1::VoucherResource).serialize_to_hash(@voucher_resources)

	end

	def spa_vouchers
		hotel = EstablishmentType.where(name: "spas and salons").first

		hotel_vouchers = paginate hotel.vouchers.order("RANDOM()"), per_page: 30

		# render jsonapi: hotel_vouchers, class: { Voucher: Api::V1::SerializableVoucher }

		context = { user: current_api_v1_user}
		@voucher_resources = hotel_vouchers.map { |voucher| Api::V1::VoucherResource.new(voucher, context) }

		render json: JSONAPI::ResourceSerializer.new(Api::V1::VoucherResource).serialize_to_hash(@voucher_resources)
	end

	def restaurant_vouchers
		hotel = EstablishmentType.where( name: "restaurants").first

		hotel_vouchers = paginate hotel.vouchers.order("RANDOM()"), per_page: 30

		# render jsonapi: hotel_vouchers, class: { Voucher: Api::V1::SerializableVoucher }
		context = { user: current_api_v1_user}
		@voucher_resources = hotel_vouchers.map { |voucher| Api::V1::VoucherResource.new(voucher, context) }

		render json: JSONAPI::ResourceSerializer.new(Api::V1::VoucherResource).serialize_to_hash(@voucher_resources)
	end

	def me
		
	end

	private

	def render_data array
		render json: { data: array }
	end

	def ensure_voucher_params_exists
		ensure_param_exists :name
	end

	def ensure_param_exists(param)
		return unless params[param].blank?
		render json:{ error: 
					{success: false, message: "Missing #{param} parameter"}
			}, status: :unprocessable_entity
	end

	
end

app/helpers/admin/establishment_types_helper.rb
module Admin::EstablishmentTypesHelper
end

app/helpers/api/v1/establishment_type_helper.rb
module Api::V1::EstablishmentTypeHelper
end

app/views/admin/establishment_types/_form.html.haml
-# = simple_form_for(@admin_establishment_type) do |f|
-#   = f.error_notification

-#   .form-inputs

-#   .form-actions
-#     = f.button :submit


.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        %h3.box-title Provide Establishment Type details
      %form{:lpformnum => "1", :role => "form"}
      = simple_form_for [:admin, @admin_establishment_type] do |f|
        - if @admin_establishment_type.errors.any?
          #error_explanation
            %h2= "#{pluralize(@admin_establishment_type.errors.count, "error")} prohibited this from being saved:"
            %ul
              - @admin_establishment_type.errors.full_messages.each do |message|
                %li= message
        %form{:_lpchecked => "1", :lpformnum => "1", :role => "form"}
          .box-body
            .row
              .col-md-6
                .form-group
                  %label{:for => "exampleInputEmail1"} Name
                  / = f.label :name
                  = f.text_field :name, class: "form-control", placeholder: "Enter name"
              .col-md-6
                .form-group
                  %label{:for => "exampleInputPassword1"} Description
                  = f.text_field :description, class: "form-control", placeholder: "Enter Description"
            .row
          / /.box-body
          .box-footer
            = f.submit class: "btn btn-primary"

app/views/admin/establishment_types/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Type List
        .box-tools.pull-right
          .digg_pagination
            = will_paginate types 
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            %br
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 182px;", :tabindex => "0"} Name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Description
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} App Availability
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 250px;", :tabindex => "0"} Options
                %tbody
                  - types.each do |type|

                    %tr{:class => "#{cycle('even', 'odd')}"}
                      %td.sorting_1= type.name.camelize
                      
                      %td= type.description
                      %td
                        - if type.available
                          %span.pull-left.badge.bg-green available to users
                        -else
                          %span.pull-right.badge.bg-grey unavailable
                       
                      %td 
                        -if current_admin && current_admin.is_moderator?
                          = link_to 'Edit', edit_admin_establishment_type_path(type), class: "label label-default"
                          = link_to "Details", admin_establishment_type_path(type), class: "label label-warning"                         
                          = link_to 'Delete', admin_establishment_path(type), :method => :delete, :data => { :confirm => 'Deleting will destroy associated Establishments, Are you sure?' }, class: "label label-danger"
                        -elsif current_admin && current_admin.is_admin?
                          = link_to 'Edit', edit_admin_establishment_type_path(type), class: "label label-default"
                          = link_to "Details", admin_establishment_type_path(type), class: "label label-warning"
                          = link_to 'Delete', admin_establishment_type_path(type), :method => :delete, :data => { :confirm => 'Deleting will destroy associated Establishments, Are you sure?' }, class: "label label-danger"
                          -if type.available
                            = link_to "Make unavailable", admin_establishment_type_activate_deactivate_type_path(type), class: "label label-default"
                          -else
                            = link_to "Make available", admin_establishment_type_activate_deactivate_type_path(type), class: "label label-success"

                %tfoot
                  %tr
                    %th{:colspan => "1", :rowspan => "1"} Name
                    %th{:colspan => "1", :rowspan => "1"} Description
                    %th{:colspan => "1", :rowspan => "1"} App Availability
                    %th{:colspan => "1", :rowspan => "1"} Options
          .row
            .col-sm-5
              .page_info
                = page_entries_info types
            .col-sm-7
              .digg_pagination
                = will_paginate types 
      / /.box-body
    / /.box
  / /.col

app/views/admin/establishment_types/edit.html.haml
%h1 Editing admin_establishment_type

= render 'form'

= link_to 'Show', admin_establishment_type_path
\|
= link_to 'Back', admin_establishment_types_path

app/views/admin/establishment_types/index.html.haml
%section.content-header
  %h1
    DisCoucher Establishment Types
    %small #{@category ? @category : @admin_establishment_types.count }
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Level
    %li.active Here
%br

%br
#partial_page
  =render "admin/establishment_types/table", types: @admin_establishment_types #the table that was previously here was extracted to the partial to be DRY. seems like I needed it more than I thought! :-)

%br
-if current_admin && current_admin.is_previlaged?
  %p=link_to 'New Type', new_admin_establishment_type_path, class: "btn btn-primary"

app/views/admin/establishment_types/new.html.haml
%h1 Create a New Cartegory

= render 'form'

= link_to 'Back', admin_establishment_types_path

app/views/admin/establishment_types/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_establishment_type_path(@admin_establishment_type)
\|
= link_to 'Back', admin_establishment_types_path